# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LIstSampleIOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LIstSampleIOS
  #  pod 'Alamofire'
  pod 'Moya', '~> 15.0'


  target 'LIstSampleIOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LIstSampleIOSUITests' do
    # Pods for testing
  end

end
